//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard_User
    {
        public long id { get; set; }
        public long userId { get; set; }
        public long creditCardId { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual User_Table User_Table { get; set; }
    }
}
