//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label_Comment
    {
        public long id { get; set; }
        public long commentId { get; set; }
        public long labId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Label Label { get; set; }
    }
}
