//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public long id { get; set; }
        public short quantity { get; set; }
        public decimal price { get; set; }
        public long productId { get; set; }
        public long orderId { get; set; }
    
        public virtual Order_Table Order_Table { get; set; }
        public virtual Product Product { get; set; }
    }
}
